name: run tests Android CI

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [33]
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Enable KVM group permissions
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Set Up JDK Environment
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: playstore
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -accel on -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: ./gradlew app:connectedDebugAndroidTest

      - name: Generate Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Report on ${{ matrix.api-level }}
          path: app/build/outputs/androidTest-results/connected/*.xml
          reporter: java-junit
