name: Read and Parse JSON

on:
  workflow_dispatch:
    inputs:
      url_path:
        default: https://support.oneskyapp.com/hc/en-us/article_attachments/202761727
        description: Input subset of tests for testing
        required: false

jobs:
  read_json:
    runs-on: ubuntu-latest
    steps:
      - name: Read JSON from URL
        id: read_json
        run: |
          content=$(curl -sL ${{ inputs.url_path }})
          delimiter="$(openssl rand -hex 8)"
          echo "json_content<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "$content" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"
          # echo "::set-output name=json_content::$content"

      - name: Parse JSON
        id: parse_json
        run: |
          echo "question: ${{ fromJson(steps.read_json.outputs.json_content).quiz.maths.q1.question }}"
          # fromJSON(toJSON(matrix))
